import { StatsPieChart } from '../../../components/statsPieChart/StatsPieChart';
import { Metadata } from 'next';

const users = [
	{ name: 'Active', value: 1 },
	{ name: 'Unverified', value: 17 },
	{ name: 'Banned', value: 1 },
];

export const metadata: Metadata = {
	title: 'Statistics',
	description: 'Generated by create turbo',
};

const API_URL = process.env['NEXT_PUBLIC_API_URL'];

const getUsers = async () => {
	const res = await fetch(`${API_URL}/users`, {
		method: 'GET',
		cache: 'no-cache',
	});

	const data = await res.json();

	function countUsersWithStatus(
		users: { name: string; status: string }[],
		status: string,
	): number {
		const filteredUsers = users.filter((user) => user.status === status);
		return filteredUsers.length;
	}

	const activeUsers = countUsersWithStatus(data, 'ACTIVE');
	const bannedUsers = countUsersWithStatus(data, 'BLOCKED');
	const unverifiedUsers = countUsersWithStatus(data, 'UNVERIFIED');

	console.log(activeUsers, bannedUsers, unverifiedUsers);

	return [
		{ name: 'Active', value: activeUsers },
		{ name: 'Unverified', value: unverifiedUsers },
		{ name: 'Banned', value: bannedUsers },
	];
};

const Statistics = async () => {
	const data = await getUsers();

	return (
		<>
			<h1>Stats</h1>
			<StatsPieChart title={'Users'} data={data} />
		</>
	);
};

export default Statistics;
