import '../styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import type { ReactNode } from 'react';
import { Provider } from '../components/provider/Provider';
import { authOptions } from './api/auth/[...nextauth]/route';
import { getServerSession } from 'next-auth/next';
import { Toaster } from 'sonner';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Turborepo',
	description: 'Generated by create turbo',
};

type RootLayoutProps = {
	children: ReactNode;
};

const RootLayout = async ({ children }: RootLayoutProps) => {
	const session = await getServerSession(authOptions);

	return (
		<html lang="en" className="light bg-lightBlue">
			<body className={inter.className}>
				<Toaster richColors={true} />
				<Provider session={session}>{children}</Provider>
				{/*<Footer />*/}
			</body>
		</html>
	);
};

export default RootLayout;
