import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Page Not Found',
	description: 'Generated by create turbo',
};

const PageNotFound = () => {
	return (
		<section className="flex min-h-screen overflow-hidden justify-center items-center">
			<h1 className="font-bold">
				Error <span className="text-purple">404</span>
			</h1>
		</section>
	);
};

export default PageNotFound;
