import { LoginPage } from '@/components/loginPage/LoginPage';
import type { Metadata } from 'next';
import { getServerSession } from 'next-auth/next';
import { authOptions } from '../../api/auth/[...nextauth]/route';
import { redirect } from 'next/navigation';

export const metadata: Metadata = {
	title: 'Sign in to your account',
	description: 'Generated by create turbo',
};

const SignInPage = async () => {
	const session = await getServerSession(authOptions);

	if (session) {
		redirect('/profile');
	}

	return <LoginPage />;
};

export default SignInPage;
