import type { Metadata } from 'next';
import { UsersTable } from '../../../components/usersTable/UsersTable';

export const metadata: Metadata = {
	title: 'All users',
	description: 'Generated by create turbo',
};

type UsersPageProps = {
	searchParams: {
		search: string;
		rowsPerPage: string;
		page: string;
	};
};

const Users = async ({ searchParams }: UsersPageProps) => {
	return (
		<div>
			<h1>Users</h1>
			<UsersTable filters={searchParams} />
		</div>
	);
};

export default Users;
