import type { Metadata } from 'next';
import { UsersTable } from '../../../components/usersTable/UsersTable';

export const metadata: Metadata = {
	title: 'All users',
	description: 'Generated by create turbo',
};

const API_URL = process.env.NEXT_PUBLIC_API_URL;

const Users = async () => {
	const res = await fetch(`${API_URL}/users`, {
		method: 'GET',
		cache: 'no-cache',
	});

	const usersData = await res.json();

	return (
		<div>
			<h1>Users</h1>
			<UsersTable users={usersData} />
		</div>
	);
};

export default Users;
