import type { Metadata } from 'next';
import { UsersTable } from '../../../components/usersTable/UsersTable';

export const metadata: Metadata = {
	title: 'All users',
	description: 'Generated by create turbo',
};

const API_URL = process.env.NEXT_PUBLIC_API_URL;

type UsersPageProps = {
	searchParams: {
		search: string;
		rowsPerPage: string;
		page: string;
	};
};

const Users = async ({ searchParams }: UsersPageProps) => {
	const res = await fetch(`${API_URL}/users`, {
		method: 'GET',
		cache: 'no-cache',
	});

	const usersData = await res.json();

	return (
		<div>
			<h1>Users</h1>
			<UsersTable users={usersData} filters={searchParams} />
		</div>
	);
};

export default Users;
