import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Dashboard | EMS',
	description: 'Generated by create turbo',
};

const Dashboard = () => {
	return (
		<>
			<h1>Dashboard</h1>
		</>
	);
};

export default Dashboard;
