import type { Metadata } from 'next';
import { getServerSession } from 'next-auth/next';
import { authOptions } from '../../api/auth/[...nextauth]/route';
import { redirect } from 'next/navigation';
import { RegisterPage } from '../../../components/registerPage/RegisterPage';

export const metadata: Metadata = {
	title: 'Create your account',
	description: 'Generated by create turbo',
};

const SignInPage = async () => {
	const session = await getServerSession(authOptions);

	if (session) {
		redirect('/profile');
	}

	return <RegisterPage />;
};

export default SignInPage;
