import type { Metadata } from 'next';
import { EventsList } from '@/components/eventsList/EventsList';

export const metadata: Metadata = {
	title: 'My events',
	description: 'Generated by create turbo',
};

const MyEventsPage = () => {
	return <EventsList />;
};

export default MyEventsPage;
